Replace yay with paru

diff --git a/.config/yadm/bootstrap b/.config/yadm/bootstrap
--- a/.config/yadm/bootstrap
+++ b/.config/yadm/bootstrap
@@ -16,8 +16,8 @@ yadm submodule update --recursive --init
 
 #Installing packages
 
-if command -v yay >/dev/null 2>&1; then
-	AUR="yay"
+if command -v paru >/dev/null 2>&1; then
+	AUR="paru"
 	AURARGS=( \
 		-Syyu
 		--needed
@@ -28,16 +28,16 @@ if command -v yay >/dev/null 2>&1; then
 		--noconfirm
 	)
 else
-	echo "Couldn't find yay" >&2
+	echo "Couldn't find paru" >&2
 	exit 2
 fi
 
 echo "Installing packages"
 
 source "$YADM_PATH/pacman-packages.sh"
-source "$YADM_PATH/yay-packages.sh"
+source "$YADM_PATH/aur-packages.sh"
 
-$AUR ${AURARGS[@]} ${PACMAN_PACKAGES[@]} ${YAY_PACKAGES[@]}
+$AUR ${AURARGS[@]} ${PACMAN_PACKAGES[@]} ${AUR_PACKAGES[@]}
 
 # Set calibre version
 sudo calibre-alternatives set 3
